sudo: false
language: node_js
node_js:
  - "8"
env:
  - CXX=g++-5
before_install:
  - npm install -g node-gyp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - gcc-5
